# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pointsheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dayweek', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thusday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('checkin', models.TimeField()),
                ('checkout_lunch', models.TimeField(null=True)),
                ('checkin_lunch', models.TimeField(null=True)),
                ('checkout', models.TimeField()),
                ('is_holiday', models.BooleanField(default=False)),
                ('type_absence', models.CharField(choices=[('1', 'Medical appointment'), ('2', 'Personal matters'), ('3', 'Day off')], max_length=3)),
                ('checkin_absence', models.TimeField(null=True)),
                ('checkout_absence', models.TimeField(null=True)),
                ('justification_absence', models.TextField(max_length=5000, null=True)),
                ('file_link', models.URLField(max_length=2000, null=True)),
                ('pointsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointsheet.Pointsheet')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together=set([('date', 'pointsheet')]),
        ),
        migrations.AlterIndexTogether(
            name='release',
            index_together=set([('date', 'dayweek', 'pointsheet')]),
        ),
    ]
