# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='pointsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointsheet.Pointsheet'),
        ),
        migrations.AlterField(
            model_name='release',
            name='type_absence',
            field=models.CharField(blank=True, choices=[('1', 'Medical appointment'), ('2', 'Personal matters'), ('3', 'Day off')], max_length=3, null=True),
        ),
    ]
